config/routes.rb
Rails.application.routes.draw do
  root to: 'movies#index'
  devise_for :users

  resources :movies do
    resources :reviews
    # resources :casts, only: [:new, :create, :show] 
    resources :star_casts 
  end
  resources :casts

  
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cast.rb
class Cast < ApplicationRecord
  has_many :star_casts
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :reviews, dependent: :destroy
  has_one_attached :picture
  belongs_to :user
  has_many :star_cast
 
  
end

app/models/review.rb
class Review < ApplicationRecord
    belongs_to :movie
    belongs_to :user
    validates :content, presence: true
    validates :rating, presence: true, inclusion: { in: 1..5 }
  end
  

app/models/star_cast.rb
class StarCast < ApplicationRecord
  self.table_name = :star_casts
   belongs_to :movie
   belongs_to :cast
   validates :role_name, :name, presence: true
 end
 

app/models/user.rb
class User < ApplicationRecord
  has_many :reviews, dependent: :destroy
  has_many :movies, dependent: :destroy

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  ADMIN_EMAILS = ['shubham@gmail.com']

  def admin?
    ADMIN_EMAILS.include?(self.email)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  before_action :authenticate_user!
    
end

app/controllers/casts_controller.rb
class CastsController < ApplicationController
  before_action :set_cast, only: [:show, :update]
  before_action :set_movie, only: [:new, :create]

  def index
    @casts = Cast.all
  end

  def show

  end

  def new
    @cast = Cast.new
  end

  def create
    @cast = Cast.new(cast_params)

    if @cast.save
      redirect_to @cast, notice: 'Cast was successfully created.'
    else
      render :new
    end
  end

  def update
    if @cast.update(cast_params)
      redirect_to @cast, notice: 'Cast was successfully updated.'
    else
      render :edit
    end
  end

  private

  def set_cast
    @cast = Cast.find(params[:id])
  end

  def cast_params
    params.require(:cast).permit(:first_name, :last_name, :date_of_birth, :place_of_birth, :biography, :gender, :nationality, :height, :weight, :social_media_links, :profile_picture)
  end

  def set_movie
    @movie = Movie.find_by_id(params[:movie_id])
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_movie, only: [:show, :edit, :update, :destroy]
  
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  def index

    @movies = Movie.all
  end

  def show
    @review = Review.new(movie: @movie)
    render json: @review
  end

  def new
    @movie = Movie.new
  end

  def create
    @movie = Movie.new(movie_params.merge(user_id: current_user.id))

    if @movie.save
      UserMailer.with(user: current_user).registration_confirmation.deliver
      redirect_to @movie, notice: 'Movie was successfully created.'
    else
      render :new
    end
  end

  def edit
  end

  def update

    if @movie.update(movie_params)
      redirect_to @movie, notice: 'Movie was successfully updated.'
    else
      render :edit
    end
  end

  def destroy

    if @movie.destroy
      redirect_to movies_url, notice: 'Movie was successfully deleted.'
    else
      redirect_to movies_path, notice: 'You cannot delete this movie.'
    end
  end

  private

  def user_not_authorized
    flash[:alert] = 'You are not authorized to perform this action.'
    redirect_to(request.referrer || root_path)
  end

  def set_movie
    @movie = Movie.find(params[:id])
  end

  def movie_params
    params.require(:movie).permit(:title, :description, :picture)
  end
end

app/controllers/require 'rails_helper'.rb
require 'rails_helper'

RSpec.describe MoviesController, type: :controller do

  
  # describe "POST #create" do
  #   context "with valid attributes" do
  #     it "creates a new movie" do
  #       user = FactoryBot.create(:user)
  #       sign_in user

  #       expect {
  #         post :create, params: { movie: FactoryBot.create(:movie) }
  #       }.to change(Movie, :count).by(1)

  #       expect(response).to redirect_to(assigns(:movie))
  #       expect(flash[:notice]).to eq('Movie was successfully created.')
  #     end
  #   end

  #   context "with invalid attributes" do
  #     it "does not create a new movie" do
  #       user = FactoryBot.create(:user)
  #       sign_in user

  #       expect {
  #         post :create, params: { movie: FactoryBot.attributes_for(:movie, title: nil) }
  #       }.to_not change(Movie, :count)

  #       expect(response).to render_template(:new)
  #     end
  #   end
  # end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_movie
  before_action :set_review, only: [:edit, :update, :destroy]

  def create
    if current_user != @movie.user
      @review = @movie.reviews.new(review_params)
      @review.user = current_user
      
      if @review.save
        redirect_to @movie, notice: 'Review was successfully created.'
      else
        redirect_to @movie, alert: 'Review could not be saved.'
      end
    else
      redirect_to @movie, alert: 'You cannot give a review for your own movie.'
    end
  end

  def edit
    
  end

  def update
    if @review.update(review_params)
      redirect_to @movie, notice: 'Review was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @review.destroy
    redirect_to @movie, notice: 'Review was successfully deleted.'
  end

  private

  def set_movie
    @movie = Movie.find(params[:movie_id])
  end

  def set_review
    @review = @movie.reviews.find(params[:id])
  end

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController
    def create
      super do |user|
        flash[:success] = "Signed in successfully."
      end
    end
  
    def destroy
      super do |user|
        flash[:notice] = "Signed out successfully."
      end
    end
  end
  

app/controllers/star_casts_controller.rb
class StarCastsController < ApplicationController
    before_action :set_star_cast, only: [:show, :update]
      before_action :set_movie, only: [:new, :create]

  
    def index
      @star_casts = StarCast.all
    end
  
    def show
      # This will render app/views/star_casts/show.html.erb
    end
  
    def new
      @star_cast = StarCast.new
    end
  
    def create 
      @star_cast = @movie.star_cast.build(star_cast_params)

      if @star_cast.save
        redirect_to root_path, notice: 'Star Cast was successfully created.'
      else
        render :new
      end
    end
  
    def update
      if @star_cast.update(star_cast_params)
        redirect_to @star_cast, notice: 'Star Cast was successfully updated.'
      else
        render :edit
      end
    end
  
    private
      def set_star_cast
        binding.pry
        @star_cast = StarCast.find(params[:id])
      end

     def set_movie
      @movie = Movie.find(params[:movie_id])
      unless @movie
        redirect_to movies_path, alert: 'Movie not found.'
      end
    end
  
      def star_cast_params
        params.require(:star_cast).permit(:role_name, :name , :cast_id, :movie_id)
      end
  end
  

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/casts_helper.rb
module CastsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/star_casts_helper.rb
module StarCastsHelper
end

app/views/casts/index.html.erb
<h1>List of Cast Members</h1>

<table>
  <thead>
    <tr>
      <th>First Name</th>
      <th>Last Name</th>
      <th>Date of Birth</th>
      <!-- Add other relevant column headers -->
    </tr>
  </thead>
  <tbody>
    <% @casts.each do |cast| %>
      <tr>
        <td><%= cast.first_name %></td>
        <td><%= cast.last_name %></td>
        <td><%= cast.date_of_birth %></td>
        <!-- Add other relevant data cells -->
      </tr>
    <% end %>
  </tbody>
</table>

app/views/casts/new.html.erb
<h1>New Cast Member</h1>

<%= form_with(model: [@movie, @cast], url: casts_path(@movie), local: true) do |form| %>
  <% if @cast.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cast.errors.count, "error") %> prohibited this cast member from being saved:</h2>
      <ul>
        <% @cast.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name %>
  </div>

  <div class="field">
    <%= form.label :date_of_birth %>
    <%= form.date_field :date_of_birth %>
  </div>
  <!-- Add other fields as needed -->

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/casts/show.html.erb
<h1>Cast Member Details</h1>

<div>
  <strong>First Name:</strong>
  <%= @cast.first_name %>
</div>

<div>
  <strong>Last Name:</strong>
  <%= @cast.last_name %>
</div>

<div>
  <strong>Date of Birth:</strong>
  <%= @cast.date_of_birth %>
</div>

<!-- Add other attributes as needed -->

<%= link_to 'Edit', edit_cast_path %> |
<%= link_to 'Back', casts_path(@movie) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>MovieReview</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_importmap_tags %>

  <!-- Add the Bootstrap CSS link here -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"
    integrity="sha384-rbs5iGArwFkR5FO9E5hAK1u3eYfN8E5YTQT0vKtfKtAVyRTfiGgCyBqAgoM/xrF" crossorigin="anonymous">

</head>

<body>
  <% if user_signed_in? %>
    <div class="text-right mt-2">
      <%= button_to 'Sign out', destroy_user_session_path, method: :delete, class: 'btn btn-danger' %>
    </div>
  <% else %>
    <div class="text-right mt-2">
      <%= button_to 'Sign in', new_user_session_path, class: 'btn btn-primary' %>
    </div>
  <% end %>

  <%= yield %>

  <!-- Add the Bootstrap JS and Popper.js scripts at the end of the body -->
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
    integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js"
    integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+"
    crossorigin="anonymous"></script>
</body>

</html>

app/views/movies/_form.html.erb
<%= form_with(model: @movie, local: true) do |form| %>
    <% if @movie.errors.any? %>
      
    <% end %>
  
    <div>
      <%= form.label :title %>
      <%= form.text_field :title %>
    </div>
  
    <div>
      <%= form.label :description %>
      <%= form.text_area :description %>
    </div>
  
    <div>
      <%= form.label :picture %>
      <%= form.file_field :picture %>
    </div>
  
    <div>
      <%= form.submit 'Save Movie' %>
    </div>
  <% end %>
  

app/views/movies/edit.html.erb
<h1>Edit Movie</h1>

<%= render 'form' %>

<%= link_to 'Back', movies_path %>

app/views/movies/index.html.erb
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Movies</title>
  <%= stylesheet_link_tag 'index_styles', media: 'all', 'data-turbolinks-track': 'reload' %>
  <!-- You can include other stylesheets or inline styles here -->
</head>

<body>

  <header>  
    <h1>Movies</h1>
  </header>
  <button type="button" class="unique-button" onclick="location.href = 'http://127.0.0.1:3000/movies/new';">New Movie</button>
  <%= link_to 'Add Cast', new_cast_path %>

  <main>
  
    <% @movies.each do |movie| %>
      <div class="movie">
        <h2><%= link_to movie.title, movie_path(movie.id) %></h2>
        <h4><%= "Total Reviews:#{movie.reviews.count}" %></h4>
        
        <% if movie.reviews.count > 0 %>
          <h4>
            <% avg_rating = movie.reviews.pluck(:rating).sum / movie.reviews.count %>
            <%= "Avg Rating: " %>
            <% avg_rating.times do %>
              ⭐
            <% end %>
            
          </h4>
        <% else %>
          <h4><%= "Avg Rating: No reviews yet*" %></h4>
        <% end %>

        <%= link_to "Read Reviews", movie_path(movie) %>
        <%= link_to 'Add Star Cast Member', new_movie_star_cast_path(movie_id: movie.id) %>
        <% movie.star_cast.each do |star_cast| %>
          <%= link_to 'View Star Cast Details', movie_star_cast_path(movie_id: movie.id, id: star_cast.id) %>
        <% end %>

      </div>
      <div class="movie-details">
        <% if movie.picture.attached? %>
          <%= image_tag movie.picture, style: "width:100px;height:100px" %>
        <% end %>
      </div>
    <% end %>

  </main>

  <footer>
    <%= paginate @movies %>
  </footer>

</body>

</html>

app/views/movies/new.html.erb
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>New Movie To Add</title>
  
  <%= stylesheet_link_tag 'new_movie_styles', media: 'all', 'data-turbolinks-track': 'reload' %>
  <!-- You can include other stylesheets or inline styles here -->
</head>

<body>

  <header>
    <h1>New Movie To Add</h1>
  </header>

  <main>
    <%= render 'form' %>
  </main>

  <footer>
    <%= link_to 'Back', movies_path %>
  </footer>

</body>

</html>

app/views/movies/show.html.erb
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= @movie.title %></title>
  <%= stylesheet_link_tag 'show_movie_styles', media: 'all', 'data-turbolinks-track': 'reload' %>
  <!-- You can include other stylesheets or inline styles here -->
</head>

<body>

  <header>
    <h1><%= @movie.title %></h1>
  </header>

  <main>
    <div class="movie-details">
      <p><strong>Description:</strong> <%= @movie.description %></p>
      <% if @movie.picture.attached? %>
        <%= image_tag @movie.picture %>
      <% end %>
    </div>

    <div class="reviews-section">
      <h2>Reviews</h2>
      <%= render @movie.reviews %>
    </div>

    <% if user_signed_in? && @movie.user_id == current_user.id%>
      <div class="text-right">
        <%= link_to 'Edit', edit_movie_path(@movie), class: 'btn btn-primary' %>
        <%= button_to 'Delete', @movie, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
      </div>
    <% end %>
    <%= render 'reviews/form', movie: @movie %>
    <%= render 'casts/form', movie: @movie %>
  </main>

  <footer>
    <%= link_to 'Back', movies_path %>
  </footer>

</body>

</html>

app/views/reviews/_form.html.erb
<%= form_with(model: [@movie, @review], local: true, url: movie_reviews_path(@movie)) do |form| %>
    <% if @review.errors.any? %>
      <div>
        <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>
  
        <ul>
          <% @review.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  
    <div>
      <%= form.label :content %>
      <%= form.text_area :content %>
    </div>
  
    <div>
      <%= form.label :rating %>
      <%= form.number_field :rating, in: 1..5 %>
    </div>
  
    <div>
      <%= form.submit 'Add Review' %>
    </div>
  <% end %>
  

app/views/reviews/_review.html.erb
<div>
  <p><strong>User:</strong> <%= review.user&.email %></p>
  <p><strong>Content:</strong> <%= review.content %></p>
  <p><strong>Rating:</strong> <%= review.rating %></p>
</div>

app/views/reviews/new.html.erb
<!-- app/views/reviews/new.html.erb -->

<%= form_with(model: @review, local: true) do |form| %>
  <!-- other form fields... -->

  <div class="field">
    <%= form.label :stars %>
    <%= form.number_field :stars, in: 1..5 %>
  </div>

  <div class="field">
    <%= form.label :comment %>
    <%= form.text_area :comment %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/shared/_star_rating.html.erb
<% rating ||= 0 %>
<% (1..5).each do |i| %>
  <% if rating >= i %>
    <span class="fas fa-star"></span>
  <% else %>
    <span class="far fa-star"></span>
  <% end %>
<% end %>

app/views/star_casts/index.html.erb
<h1>List of Star Cast Members</h1>

<table>
  <thead>
    <tr>
      <th>Actor/Actress Name</th>
      <th>Movie</th>
      <th>Role</th>
      <!-- Add other relevant column headers -->
    </tr>
  </thead>
  <tbody>
    <% @star_casts.each do |star_cast| %>
      <tr>
        <td><%= star_cast.actor_name %></td>
        <td><%= star_cast.movie.title %></td>
        <td><%= star_cast.role %></td>
        <!-- Add other relevant data cells -->
      </tr>
    <% end %>
  </tbody>
</table>

app/views/star_casts/new.html.erb
<h1>Add Star Cast</h1>

<%= form_with(model: [@movie, StarCast.new], url: movie_star_casts_path(@movie), local: true) do |form| %>
  <% if @star_cast.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@star_cast.errors.count, "error") %> prohibited this star cast member from being saved:</h2>
      <ul>
        <% @star_cast.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :cast_id, "Select Cast Member" %>
    <%= form.collection_select :cast_id, Cast.all, :id, :first_name, prompt: "Select a cast member" %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :role_name %>
    <%= form.text_field :role_name %>
  </div>



  <div class="field">
    <%= form.label :cast_id, "Select movie" %>
    <%= form.collection_select :movie_id, Movie.all, :id, :title, prompt: "Select a movie" %>
  </div>

  <!-- Add other fields as needed -->

  <div class="actions">
    <%= form.submit "Add Star Cast" %>
  </div>
<% end %>

app/views/star_casts/show.html.erb
<!-- app/views/star_casts/show.html.erb -->
<h1>Star Cast Details</h1>
<%binding.pry%>
<p><strong>Name:</strong> <%= @star_cast.name %></p>
<p><strong>Role Name:</strong> <%= @star_cast.role_name %></p>
<!-- Add any other details you want to display -->